# Generated by Django 5.2.15 on 2026-07-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrestashopCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prestashop_id", models.PositiveIntegerField(unique=True)),
                ("firstname", models.CharField(blank=True, max_length=255)),
                ("lastname", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_add", models.DateTimeField()),
                ("address1", models.CharField(blank=True, max_length=255)),
                ("postcode", models.CharField(blank=True, max_length=32)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("phone_mobile", models.CharField(blank=True, max_length=32)),
                ("dni", models.CharField(blank=True, max_length=32)),
                ("vat_number", models.CharField(blank=True, max_length=32)),
                ("last_snapshot_at", models.DateTimeField()),
                (
                    "export_status",
                    models.CharField(
                        choices=[
                            ("never", "Never exported"),
                            ("succeeded", "Exported"),
                            ("failed", "Failed"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("exported_to_icg_at", models.DateTimeField(blank=True, null=True)),
                ("last_export_error", models.TextField(blank=True)),
                ("last_export_inserted", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_add", "-prestashop_id"],
            },
        ),
        migrations.CreateModel(
            name="PrestashopOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prestashop_id", models.PositiveIntegerField(unique=True)),
                ("payment", models.CharField(blank=True, max_length=255)),
                ("date_add", models.DateTimeField()),
                ("total_paid_tax_incl", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_shipping_tax_incl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_shipping_tax_excl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_snapshot_at", models.DateTimeField()),
                (
                    "export_status",
                    models.CharField(
                        choices=[
                            ("never", "Never exported"),
                            ("succeeded", "Exported"),
                            ("failed", "Failed"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("exported_to_icg_at", models.DateTimeField(blank=True, null=True)),
                ("last_export_error", models.TextField(blank=True)),
                ("inserted_rows", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="sales.prestashopcustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_add", "-prestashop_id"],
            },
        ),
        migrations.CreateModel(
            name="PrestashopOrderDiscountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount_tax_incl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount_tax_excl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="sales.prestashoporder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "position"), name="sales_unique_order_discount_position"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrestashopOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("prestashop_product_id", models.PositiveIntegerField()),
                ("prestashop_combination_id", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price_tax_incl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price_tax_incl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.prestashoporder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "position"), name="sales_unique_order_line_position"
                    )
                ],
            },
        ),
    ]
