# Generated by Django 5.2.15 on 2026-07-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_combination_last_icg_modified_date_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestashoporderline",
            name="override_combination",
            field=models.ForeignKey(
                blank=True,
                help_text="Manually map this order line to a catalog combination when the Prestashop combination is missing from the catalog.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.combination",
            ),
        ),
    ]
