# Generated by Django 5.2.15 on 2026-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_prestashoporderline_override_combination"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestashoporderline",
            name="prestashop_order_detail_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
