# Generated by Django 5.2.15 on 2026-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_prestashoporderline_prestashop_order_detail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestashoporder",
            name="current_state",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
