import csv
import json
from collections import defaultdict
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from apps.catalog.models import Product


def _load_json(path: str | None) -> dict | list:
    if not path:
        return {}
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


class Command(BaseCommand):
    help = (
        "Aggregate conflict, unresolved, and missing reports into a shop-facing CSV "
        "ordered by the number of problematic combinations per reference."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--conflicts-json",
            help="Path to combination-conflicts.json generated by \
                    reconcile_prestashop_combinations.",
        )
        parser.add_argument(
            "--unresolved-json",
            help=(
                "Path to unresolved-combinations.json generated by "
                "report_prestashop_unresolved_combinations."
            ),
        )
        parser.add_argument(
            "--missing-reference-json",
            help=(
                "Path to missing-reference-comparison.json generated by "
                "report_prestashop_missing_reference_comparison."
            ),
        )
        parser.add_argument(
            "--output",
            required=True,
            help="Path to write the CSV report for shop staff.",
        )

    def handle(self, *args, **options):
        output_path = options["output"]
        conflicts_path = options.get("conflicts_json")
        unresolved_path = options.get("unresolved_json")
        missing_reference_path = options.get("missing_reference_json")

        if not any([conflicts_path, unresolved_path, missing_reference_path]):
            raise CommandError(
                "Provide at least one input report: --conflicts-json, --unresolved-json, or "
                "--missing-reference-json"
            )

        conflicts_payload = _load_json(conflicts_path)
        unresolved_payload = _load_json(unresolved_path)
        missing_reference_payload = _load_json(missing_reference_path)

        buckets: dict[str, dict] = defaultdict(
            lambda: {
                "reference": "",
                "conflict_count": 0,
                "missing_count": 0,
                "unresolved_count": 0,
            }
        )

        if isinstance(conflicts_payload, list):
            for item in conflicts_payload:
                reference = str(item.get("reference") or "").strip()
                if not reference:
                    continue
                buckets[reference]["reference"] = reference
                buckets[reference]["conflict_count"] += 1

        if isinstance(unresolved_payload, dict):
            for item in unresolved_payload.get("unresolved_combinations", []):
                reference = str(item.get("reference") or "").strip()
                if not reference:
                    continue
                buckets[reference]["reference"] = reference
                buckets[reference]["unresolved_count"] += 1

        if isinstance(missing_reference_payload, dict):
            for item in missing_reference_payload.get("references", []):
                reference = str(item.get("reference") or "").strip()
                if not reference:
                    continue
                buckets[reference]["reference"] = reference
                buckets[reference]["missing_count"] += int(item.get("missing_count") or 0)

        references = list(buckets.keys())
        products = Product.objects.filter(reference__in=references).select_related("manufacturer")
        product_by_reference = {product.reference: product for product in products}

        rows = []
        for reference, bucket in buckets.items():
            product = product_by_reference.get(reference)
            total = bucket["conflict_count"] + bucket["missing_count"] + bucket["unresolved_count"]
            issue_types = []
            if bucket["conflict_count"]:
                issue_types.append("conflicts")
            if bucket["missing_count"]:
                issue_types.append("missing")
            if bucket["unresolved_count"]:
                issue_types.append("unresolved")

            rows.append(
                {
                    "reference": reference,
                    "name": product.name if product else "",
                    "manufacturer": product.manufacturer.name
                    if product and product.manufacturer
                    else "",
                    "visible_web": product.visible_web if product else "",
                    "discontinued": product.discontinued if product else "",
                    "prestashop_product_id": product.prestashop_id if product else "",
                    "total_problem_combinations": total,
                    "conflict_count": bucket["conflict_count"],
                    "missing_count": bucket["missing_count"],
                    "unresolved_count": bucket["unresolved_count"],
                    "issue_types": ", ".join(issue_types),
                    "suggested_action": "Review variants; consider visible_web=False until fixed",
                }
            )

        rows.sort(
            key=lambda row: (
                -int(row["total_problem_combinations"]),
                -int(row["missing_count"]),
                row["reference"],
            )
        )

        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        fieldnames = [
            "reference",
            "name",
            "manufacturer",
            "visible_web",
            "discontinued",
            "prestashop_product_id",
            "total_problem_combinations",
            "conflict_count",
            "missing_count",
            "unresolved_count",
            "issue_types",
            "suggested_action",
        ]
        with output.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

        self.stdout.write(self.style.SUCCESS(f"Wrote shop report to {output_path}"))
        self.stdout.write(
            self.style.SUCCESS(
                f"Shop report summary: references={len(rows)} total_problem_combinations="
                f"{sum(int(row['total_problem_combinations']) for row in rows)}"
            )
        )
