# Generated by Django 5.2 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("import_products", "Import products"),
                    ("import_prices", "Import prices"),
                    ("import_stock", "Import stock"),
                    ("export_manufacturer", "Export manufacturer"),
                    ("export_product", "Export product"),
                    ("export_price", "Export price"),
                    ("export_stock", "Export stock"),
                ],
                max_length=32,
            ),
        ),
    ]
