# Generated by Django 5.1.15 on 2026-06-20 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_export_manufacturer_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lock_key", models.CharField(max_length=64, unique=True)),
                ("locked_by", models.CharField(blank=True, max_length=128)),
                ("locked_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["lock_key"],
            },
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("import_products", "Import products"),
                    ("import_prices", "Import prices"),
                    ("import_stock", "Import stock"),
                    ("export_manufacturer", "Export manufacturer"),
                    ("export_category", "Export category"),
                    ("export_product", "Export product"),
                    ("export_combination", "Export combination"),
                    ("export_price", "Export price"),
                    ("export_stock", "Export stock"),
                    ("export_discount", "Export discount"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SyncError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_key", models.CharField(max_length=128)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("transient", "Transient (retryable)"),
                            ("permanent", "Permanent"),
                            ("validation", "Validation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="sync.syncjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
