# Generated by Django 5.2 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0004_customer_sync_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synccursor",
            name="source",
            field=models.CharField(
                choices=[
                    ("products", "Products"),
                    ("prices", "Prices"),
                    ("stock", "Stock"),
                    ("customers", "Customers"),
                    ("orders", "Orders"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("import_products", "Import products"),
                    ("import_prices", "Import prices"),
                    ("import_stock", "Import stock"),
                    ("export_customer", "Export customer"),
                    ("export_order", "Export order"),
                    ("export_manufacturer", "Export manufacturer"),
                    ("export_category", "Export category"),
                    ("export_product", "Export product"),
                    ("export_combination", "Export combination"),
                    ("export_price", "Export price"),
                    ("export_stock", "Export stock"),
                    ("export_discount", "Export discount"),
                ],
                max_length=32,
            ),
        ),
    ]
