# Generated by Django 5.2 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="last_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="prestashop_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="sync_required",
            field=models.BooleanField(default=True),
        ),
    ]
