# Generated by Django 5.1.15 on 2026-06-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_manufacturer_sync_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icg_type",
                    models.CharField(help_text="size or color", max_length=32, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("prestashop_id", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["icg_type"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icg_value", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("prestashop_id", models.PositiveIntegerField(unique=True)),
                (
                    "attribute_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.attributegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["attribute_group__icg_type", "icg_value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attribute_group", "icg_value"), name="catalog_unique_group_value"
                    )
                ],
            },
        ),
    ]
