# Generated by Django 5.1.15 on 2026-06-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_taxrulemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prestashop_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("position", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("hidden", "Hidden"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        help_text="Determines how this category is used during product export. DEFAULT: assigned as default category for new products. HIDDEN: used for products not visible on the web. NORMAL: available for manual assignment.",
                        max_length=16,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_products",
                to="catalog.category",
            ),
        ),
    ]
