# Generated by Django 5.1.15 on 2026-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_category_product_categories_product_category_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="last_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="sync_required",
            field=models.BooleanField(default=True),
        ),
    ]
