# Generated by Django 5.1.15 on 2026-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_category_last_sync_error_category_last_synced_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="prestashop_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
