# Generated by Django 5.1.15 on 2026-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_category_prestashop_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Product-level discount percentage (0 = no discount). Exported as a Prestashop specific_price with reduction_type='percentage'.",
                max_digits=5,
            ),
        ),
    ]
