# Generated by Django 5.1.15 on 2026-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_add_product_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prestashop_specific_price_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Prestashop specific_price ID for the product-level discount.",
                null=True,
            ),
        ),
    ]
