# Generated by Django 5.2.15 on 2026-06-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_product_prestashop_id_combination_prestashop_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributegroup",
            options={"ordering": ["icg_type", "product__reference"]},
        ),
        migrations.AddField(
            model_name="attributegroup",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="For color groups: the product this group belongs to. Null for global size group.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_groups",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="texture_image",
            field=models.ImageField(
                blank=True,
                help_text="Texture/color swatch image shown in the attribute picker.",
                upload_to="attribute_textures/",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="texture_synced",
            field=models.BooleanField(
                default=False,
                help_text="Whether the texture image has been uploaded to PrestaShop.",
            ),
        ),
        migrations.AlterField(
            model_name="attributegroup",
            name="icg_type",
            field=models.CharField(help_text="size or color", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="attributegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", True)),
                fields=("icg_type",),
                name="unique_global_attribute_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("product", "icg_type"),
                name="unique_product_attribute_group",
            ),
        ),
    ]
