# Generated by Django 5.2.15 on 2026-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_per_product_color_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="last_icg_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="last_icg_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="last_icg_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_icg_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="last_icg_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
